packages:
  - packages/*
  - apps/*

catalog:
  '@vitejs/plugin-vue': ^6.0.3
  tsdown: ^0.18.1
  unplugin-vue: ^7.1.1
  vite: 8.0.0-beta.5
  vite-plugin-vue-devtools: ^8.0.5
  vue: 3.6.0-beta.4
  vue-jsx-vapor: ^3.0.4
  vue-tsc: ^3.2.4
  '@v-c/util': ^1.09

onlyBuiltDependencies:
  - esbuild
  - less
