packages:
  - packages/*
  - apps/*

catalog:
  '@v-c/util': ^1.0.9
  '@vitejs/plugin-vue': ^6.0.5
  '@vue/test-utils': ^2.4.6
  eslint: ^9.39.3
  jsdom: ^27.4.0
  less: ^4.6.4
  resize-observer-polyfill: ^1.5.1
  tsdown: ^0.21.2
  turbo: ^2.8.16
  unplugin-vue: ^7.1.1
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-vue-devtools: ^8.1.0
  vite-plus: ^0.1.12
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: 3.6.0-beta.4
  vue-tsc: ^3.2.5

onlyBuiltDependencies:
  - esbuild
  - less
  - simple-git-hooks

overrides:
  make-dir: ^5.1.0
  semver: ^7.0.0
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

shellEmulator: true

trustPolicy: no-downgrade
